# Fetch ubuntu image
FROM ubuntu:22.04

# Install build tools
RUN apt update && \
    apt install -y wget build-essential autoconf automake libtool patch

# Create necessary directories for mounting
RUN mkdir -p /project/src /project/tests /project/tools

# Copy only the Makefile
COPY Makefile /project/Makefile

# Copy patch file into container
COPY cpputest-set-tracing.patch /tmp/cpputest-set-tracing.patch

# Download, patch, and build CppUTest
RUN cd /project/ && \
    wget https://github.com/cpputest/cpputest/releases/download/v4.0/cpputest-4.0.tar.gz && \
    tar xf cpputest-4.0.tar.gz && \
    mv cpputest-4.0/ tools/cpputest/ && \
    cd tools/cpputest/ && \
    patch -p1 < /tmp/cpputest-set-tracing.patch && \
    autoreconf -i && \
    ./configure && \
    make

# Set the entry point
ENTRYPOINT ["make", "test", "-C", "/project/"]
