#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

// Enable nrfx_twim (I2C Master)
#define NRFX_TWIM_ENABLED 1
#define NRFX_TWIM0_ENABLED 1
#define NRFX_TWIM_DEFAULT_CONFIG_FREQUENCY NRF_TWIM_FREQ_100K
#define NRFX_TWIM_DEFAULT_CONFIG_HOLD_BUS_UNINIT 0
#define NRFX_TWIM_DEFAULT_CONFIG_IRQ_PRIORITY 6
#define NRFX_TWIM_CONFIG_LOG_ENABLED 0

// Disable unneeded features
#define NRFX_TWIM1_ENABLED 0
#define NRFX_TWIM2_ENABLED 0
#define NRFX_TWIM3_ENABLED 0

#endif // SDK_CONFIG_H